version: '3'
services:
  wacodis-wps:
    build: .
    image: wacodis/wps:1.x
    env_file:
      - wacodis.env
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G